task: 'task1' # This can be set to 'task1', 'task2' or 'task3'

path:
  # cec1_root: ???
  # exp_folder: ??? # folder to store intermediate signals and final results
  root: /mnt/parscratch/users/act23ss/clarity_CEC3_data # root folder for clarity data
  exp: /users/act23ss/clarity/data # folder to store enhanced signals and final results
  scenes_folder: ${path.root}/${task}/clarity_data/dev/scenes
  metadata_dir: ${path.root}/${task}/clarity_data/metadata
  scenes_listeners_file: ${path.metadata_dir}/scenes_listeners.dev.json
  listeners_file: ${path.metadata_dir}/listeners.json
  scenes_file: ${path.metadata_dir}/scenes.dev.json
  cec2_root: /mnt/parscratch/users/act23ss

sr: 32000
sample_rate: 44100
downsample_factor: 2
num_channels: 6
level_norm: False
wav_silence_len: 0

listener:
  # metafile: ${path.cec1_root}/clarity_CEC1_data/clarity_data/metadata/listeners.json
  metafile: ${path.metadata_dir}/listeners.json
  id: L0001
  src_pos: ff
  loudnorm: False

mc_conv_tasnet:
  N_spec: 256
  N_spat: 128 # 6 * 30
  L: 20
  B: 256
  H: 512
  P: 3
  X: 6
  R: 4
  C: 2 # num_speakers, 1 for cec1
  num_channels: 6 # should be consistent with dataloader num_channels
  norm_type: cLN
  causal: True
  mask_nonlinear: relu

# amplification model params
amplifier:
  sr: ${sample_rate}  
  nfir: 240
  n_layer: 3
  n_hidden: 512
  dropout: 0.2

fir:
  sample_rate: ${sample_rate}
  nfir: 220

den_trainer:
  optimizer:
    lr: 1e-3
  epochs: 1
  gradient_clip_val: 5.0

amp_trainer:
  optimizer:
    lr: 5e-2
  epochs: 1
  gradient_clip_val: 5.0
  stoilevel_loss:
    sr: ${sample_rate}
    alpha: 1e-4
  dhaspi_loss:
    sr: 24000
    alpha: 1
  num_sanity_val_steps: 2

# train_dataset:
#   scenes_folder: ${path.cec1_root}/clarity_CEC1_data/clarity_data/train/scenes
#   scenes_file: ${path.cec1_root}/clarity_CEC1_data/clarity_data/metadata/scenes.train.json
#   sample_rate: ${sample_rate}
#   downsample_factor: ${downsample_factor}
#   wav_sample_len: 2
#   wav_silence_len: ${wav_silence_len}
#   num_channels: ${num_channels}
#   norm: ${level_norm}

train_dataset:
  scenes_folder: ${path.root}/${task}/clarity_data/train/scenes
  scenes_file: ${path.metadata_dir}/scenes.train.json
  sample_rate: ${sample_rate}
  downsample_factor: ${downsample_factor}
  wav_sample_len: 2
  wav_silence_len: ${wav_silence_len}
  num_channels: ${num_channels}
  norm: ${level_norm}

train_loader:
  batch_size: 1
  shuffle: True
  num_workers: 10 #8 10 were before
  drop_last: true
  pin_memory: True

# dev_dataset:
#   scenes_folder: ${path.cec1_root}/clarity_CEC1_data/clarity_data/dev/scenes
#   scenes_file: ${path.cec1_root}/clarity_CEC1_data/clarity_data/metadata/scenes.dev.json
#   sample_rate: ${sample_rate}
#   downsample_factor: ${downsample_factor}
#   wav_sample_len: null
#   wav_silence_len: ${wav_silence_len}
#   num_channels: ${num_channels}
#   norm: ${level_norm}

dev_dataset:
  scenes_folder: ${path.root}/${task}/clarity_data/dev/scenes
  scenes_file: ${path.metadata_dir}/scenes.dev.json
  sample_rate: ${sample_rate}
  downsample_factor: ${downsample_factor}
  wav_sample_len: null
  wav_silence_len: ${wav_silence_len}
  num_channels: ${num_channels}
  norm: ${level_norm}

dev_loader:
  batch_size: 1
  shuffle: False
  num_workers: 10 #8 10

test_dataset:
  scenes_folder: ${path.root}/${task}/clarity_data/eval/scenes
  scenes_file: ${path.metadata_dir}/scenes_listeners.eval.json
  sample_rate: ${sample_rate}
  downsample_factor: ${downsample_factor}
  wav_sample_len: null
  wav_silence_len: 0
  num_channels: ${num_channels}
  norm: ${level_norm}
  testing: True

test_loader:
  batch_size: 1
  shuffle: False
  num_workers: 10 #8 10

soft_clip: True

evaluate:
  set_random_seed: True
  small_test: True
  first_scene: 0
  n_scenes: 0

# hydra config
hydra:
  run:
    dir: ${path.exp}
  sweep:
    dir: ${path.exp}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

defaults:
  - override hydra/launcher: cec3_submitit_local #slurm
